# Определяем upstream для балансировки нагрузки между тремя инстансами Django
events {}

http {
    upstream django {
        server django1:8000;  # Первый инстанс Django
        server django2:8000;  # Второй инстанс Django
    }

    server {
        listen 80;
        server_name _;

        root /var/www/html/build;

        # Логирование
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        # Путь до собранных статических файлов Django (например, admin)
        location /admin {
            proxy_pass http://django/admin;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Настройки кэширования статики
        location /django_static {
            root /var/www/html;  # Путь к статикам React-приложения
            expires 30d;  # Кэшировать файлы на 30 дней
            add_header Cache-Control "public, max-age=2592000, immutable";
        }

        # Путь до директории, где хранятся медиа файлы
        location /django_media {
            root /var/www/html;
            expires 30d;  # Кэшируем медиа-файлы на 30 дней (можно уменьшить, если нужно)
            add_header Cache-Control "public, max-age=2592000, immutable";
        }


        # Прокси для API запросов к Django
        location /api {
            proxy_pass http://django/api;  # Балансировка нагрузки между инстансами Django
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static {
            try_files $uri $uri/ /index.html;
            include /etc/nginx/mime.types;
            expires 1h;
            add_header Cache-Control "public, max-age=3600";
        }

        # Прокси настройки для Django
        location / {
            try_files $uri $uri/ /index.html;
            expires 1h;
            add_header Cache-Control "public, max-age=3600";
        }


        # Сжатие файлов (gzip)
        gzip on;
        gzip_types text/plain application/xml application/javascript application/x-javascript text/javascript text/css application/json;
        gzip_min_length 256;
    }
    # include "/etc/nginx/conf.d/*.conf";
}
