# Generated by Django 5.1 on 2024-08-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок вопроса')),
                ('description', models.TextField(verbose_name='Описание вопроса')),
                ('subject', models.CharField(choices=[('RU', 'Russian')], default='RU', max_length=255, verbose_name='Заголовок вопроса')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Виден ли вопрос в списке')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
