# Generated by Django 5.1.3 on 2024-12-16 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_picture_test_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='question_count',
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='questions.test', verbose_name='Тест'),
        ),
    ]
