# Generated by Django 5.1.4 on 2025-01-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_remove_customer_completed_tests'),
        ('questions', '0008_session_created_at_session_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='TestSession',
        ),
    ]
