# Generated by Django 5.1.6 on 2025-02-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_rename_session_testsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='time_spent',
            field=models.TimeField(null=True, verbose_name='Время прохождения теста'),
        ),
    ]
