# Generated by Django 5.1.7 on 2025-04-01 07:53
from django.contrib.postgres.search import SearchVectorField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0002_alter_card_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="search_vector",
            field=SearchVectorField(null=True),
        ),
        migrations.RunSQL(
            "CREATE INDEX card_search_vector_idx ON guide_card USING gin (search_vector);"
        ),
    ]
