# Generated by Django 5.1.7 on 2025-04-06 15:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0003_auto_20250401_1053"),
        ("questions", "0010_attempt_time_spent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="guide_card_search__53bf4a_gin"
            ),
        ),
    ]
