# Generated by Django 5.1.3 on 2024-12-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_completed_tests_customer_in_process_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='completed_tests',
        ),
    ]
