# Generated by Django 5.1.4 on 2025-01-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_email_alter_customer_first_name_and_more'),
        ('customers', '0008_remove_customer_completed_tests'),
    ]

    operations = [
    ]
