# Generated by Django 5.1.4 on 2025-01-06 12:26

import core.apps.customers.customer_session_model
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_merge_20250106_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='expires_in',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='refresh_expires_in',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='refresh_token',
        ),
        migrations.CreateModel(
            name='CustomerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('access_token', models.CharField(default=uuid.uuid4, max_length=255, verbose_name='Токен авторизации')),
                ('refresh_token', models.CharField(default=uuid.uuid4, max_length=255, verbose_name='Токен для обновления access token')),
                ('expires_in', models.BigIntegerField(default=core.apps.customers.customer_session_model.CustomerSession.get_expires_in, verbose_name='Время до истечения access token')),
                ('refresh_expires_in', models.BigIntegerField(default=core.apps.customers.customer_session_model.CustomerSession.get_refresh_expires_in, verbose_name='Время до истечения refresh token')),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'verbose_name': 'Сессия пользователя',
                'verbose_name_plural': 'Сессии пользователей',
            },
        ),
    ]
