# Generated by Django 5.1.7 on 2025-04-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0010_remove_customer_access_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="customers/pofile_pictures",
                verbose_name="Изображение профиля",
            ),
        ),
    ]
